---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# scPagwas

<!-- badges: start -->
<!-- badges: end -->

The goal of scPagwas is to ...

## Installation

You can install the released version of scPagwas from [CRAN](https://CRAN.R-project.org) with:

``` r
install_github("lijian13/rinds")
#install.packages("scPagwas")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}

 library(scPagwas)
 ## basic example code
 data(Genes_by_pathway_kegg)
 data(GWAS_summ_example)
 data(gtf_df)
 data(scRNAexample)
 #data(eqtls_files)
 data(chrom_ld)
 #1. OnlyTSS
 
 Pagwas<-Pagwas_main(Pagwas = NULL,
                     gwas_data = GWAS_summ_example,
                     add_eqtls="OnlyTSS",
                     block_annotation = gtf_df,
                     Single_data = scRNAexample,
                     Pathway_list=Genes_by_pathway_kegg,
                     chrom_ld = chrom_ld)
``` 

```{r pressure, echo = FALSE}
Bootstrap_P_Barplot(Pagwas=Pagwas,title = "Test scPagwas")
```

```{r pressure, echo = FALSE}

Bootstrap_estimate_Plot(Pagwas=Pagwas,figurenames = NULL)

```

```{r example}

 scPagwas<- scPagwas_main(Pagwas = Pagwas,
               #gwas_data = GWAS_summ_example,
               #add_eqtls="OnlyTSS",
               #block_annotation = gtf_df,
               #Single_data = scRNAexample,
               #Pathway_list=Genes_by_pathway_kegg,
               #chrom_ld = chrom_ld,
               simp_results=TRUE)
```

```{r pressure, echo = FALSE}
 scPagwas_Visualization(scPagwas_score = scPagwas$scPagwas_score,
                        Single_data = scRNAexample,
                        Reduction = TRUE,
                        assay = "SCT",
                        cellpercent = 0.1,
                        filename = "scPagwas_testFigure",
                        FigureType = "tsne",
                        width = 7,
                        height = 7,
                        lowColor = "#FFBC80", highColor = "#FC4F4F",
                        size = 1,
                        title = "scPagwas_score")

```


